config/routes.rb
Rails.application.routes.draw do
  root to: 'image_containers#index'
  resources :image_containers, only: %i[index new create show destroy search] do
    get 'download', on: :member
    post 'search_word', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image_container.rb
class ImageContainer < ApplicationRecord
  has_one_attached :original_image
  has_one_attached :processed_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/image_containers_controller.rb
class ImageContainersController < ApplicationController
  before_action :set_image_container, except: %i[index new create]

  def index
    @image_containers = ImageContainer.all
  end

  def show; end

  def new
    @image_container = ImageContainer.new
  end

  def create
    @image_container = ImageContainer.new(image_container_params)
    if @image_container.save
      ImageProcessingJob.perform_later(@image_container)
      redirect_to root_path, notice: 'Image uploaded successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @image_container.destroy
      redirect_to root_path, notice: 'Image Deleted Successfully'
    else
      render @image_container, status: :unprocessable_entity
    end
  end

  def download
    send_data @image_container.processed_image.download, type: 'image/png', disposition: 'attachment'
  end

  def search_word
    ImageProcessingService.new(@image_container, params[:query]).call!
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream:
          turbo_stream.update('processed-image', partial: 'processed_image', locals: { object: @image_container })
      end
    end
  end

  private

  def image_container_params
    params.require(:image_container).permit(:original_image)
  end

  def set_image_container
    @image_container = ImageContainer.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to '/404'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/image_containers/_form.html.erb
<%= form_with model: @image_container do |form| %>
  <div class="field">
    <%= form.file_field :original_image, class: 'form-control mb-3', required: true, accept:'image/*' %>
  </div>

  <div class="my-2 text-center">
    <%= link_to "Cancel", root_path, class: "btn btn-outline-dark rounded-0" %>
    <%= form.submit class: "btn btn-success rounded-0" %>
  </div>
<% end %>

app/views/image_containers/_processed_image.html.erb
<% if @image_container.processed_image.present? %>
  <div class="row">
    <div class="col-6"><h6>Processed image</h6></div>
    <div class="col-6 text-end"><%= link_to 'Download Processed Image', download_image_container_path(@image_container), class: "w-25vw" %></div>
  </div>
  <%= image_tag  @image_container.processed_image, class: "w-100" %>
<% else %>
  <h6>Your image is being processed ...</h6>
<% end %>

app/views/image_containers/index.html.erb
<div class="text-center mt-5">
  <h5>Upload an Image to process</h5>
  <%= link_to "Upload Image", new_image_container_path, class: "btn btn-success text-white rounded-0" %>


  <div class="d-flex mt-5 p-5">
    <% @image_containers.each do |image_container| %>
      <div class="border p-3">
        <div><%= image_tag image_container.original_image, class: "thumbnail-size" %></div>
        <div>
          <%= link_to 'Delete Image', image_container, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-danger" %>
          <%= link_to 'View Processed Image', image_container, class: "thumbnail-size" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/image_containers/new.html.erb
<div class="p-5">
  <h4>Select an image</h4>
  <%= render 'form' %>
</div>

app/views/image_containers/show.html.erb
<div class="p-5">
  <%= form_with(url: search_word_image_container_path(@image_container), method: :post) do |form| %>
    <div class="d-flex">
      <%= form.text_field :query, class: 'form-control rounded-0', placeholder: 'Search for a word', required: true %>
      <%= form.submit "Search", class: "btn btn-success rounded-0" %>
    </div>
  <% end %>

  <div class="row mt-4">
    <div class="col-6">
      <h6>Original image</h6>
      <%= image_tag @image_container.original_image, class: "w-100" %>
    </div>
    <div class="col-6" id="processed-image">
      <%= render 'processed_image' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imageparser</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>